version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: test_openaisafe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    networks:
      - test-network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    tmpfs:
      - /data
    networks:
      - test-network

  test-runner:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/test_openaisafe
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=test-key
      - JWT_SECRET=test-secret
    command: npm run test:all
    volumes:
      - ./coverage:/app/coverage
      - ./test-results:/app/test-results
    networks:
      - test-network

networks:
  test-network:
    driver: bridge 