use std::env;
use std::path::PathBuf;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let mut config: cbindgen::Config = Default::default();
    
    config.language = cbindgen::Language::C;
    config.style = cbindgen::Style::Both;
    config.include_guard = Some("SAFETY_ANALYSIS_H".to_string());
    config.autogen_warning = Some("/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */".to_string());
    
    cbindgen::generate_with_config(&crate_dir, config)
        .expect("Unable to generate bindings")
        .write_to_file(PathBuf::from(&crate_dir).join("safety_analysis.h"));
    
    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=Cargo.toml");
} 