#ifndef SAFETY_ANALYSIS_H
#define SAFETY_ANALYSIS_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

char *analyze_safety(const char *text, const char *context);

char *analyze_interpretability(const char *text);

void free_string(char *s);

#endif /* SAFETY_ANALYSIS_H */
